### ISSUE TITLE
feat: connection-manager peer & connection flexibility improvements via config

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/js-libp2p#2119] opened 2023-10-03 18:52 UTC
discussed in https://pl-strflt.notion.site/js-libp2p-Have-more-flexible-Peer-and-Connection-management-5f529c6b3d894226a65d747b2b7897f7?pvs=4

- Connection Manager to accept two functions as config:
    - Return a list of peers to auto-dial
        - Defaults to a list sorted by tags
    - Accept a list of open connections, return a list of connections to prune
        - Defaults to maxConnections

```[tasklist]
### Connection Manager to accept two functions as config
- [ ] Return a list of peers to auto-dial (default = list sorted by tags)
- [ ] Accept a list of open connections, return a list of connections to prune (defaults to conns with index > maxConns)
```

**Comment by maschad** [comment] 2023-10-03 19:13
This is a duplicate of https://github.com/libp2p/js-libp2p/issues/2098

**Closed by maschad** 2023-10-03 19:13 UTC
Labels: need/triage
