### ISSUE TITLE
Expose .toString() functionality on non-collision method

### ISSUE THREAD

**Issue by dapplion** [libp2p/js-libp2p#1850] opened 2023-05-04 05:08 UTC
Every single object in Typescript / Javascript has a .toString() method

Using .toString() for PeerId and Multiaddr is very dangerous since it can lead to unexpected bugs
- Crossing a worker thread boundary the instance of the object is changed so toString() results in`[Object object]` instead of an error such as `no method <method> found in object`
- During refactors, all those .toString() calls are not flagged by the compiler since every type has them

At least these two have created significant pain in Lodestar. If you want to expose .toString() for good UX I'm fine with it, but please expose the same funcionality through a name that does not collide with a method already present in all types for us

**Comment by maschad** [comment] 2023-09-19 15:40
We should rename the alias for the `toString()` method given that this interferes with a popular method name.

**Comment by SgtPooki** [comment] 2024-09-20 14:23
<details>
<summary>JS Colo 2024 discussion</summary>

* Is this a big problem? 

* it's very challenging to transfer across thread boundaries, if someone is doing that, devs/apps should be responsible for serialization and deserialization when passing through those boundaries. 
* this is a problem though.. maybe if it were day zero we would switch it, but it would be a significant impact now, when this is a problem shared by many complex objects now

</details>

Unfortunately, implementing the suggested solution would significantly disrupt library consumers. The problem is very specific, and common solutions exist in JS ecosystems. 

There are some workarounds available for any consumers facing this situation:

* if transferring across boundaries, convert to serialized/simplified form first, which you can reinflate with the correct prototype chain
* if you're really worried about accidentally using type safety due to using toString(), pull the method off the prototype of the object you're using directly: `PeerId.prototype.toString.call(myPeerId)` will throw typescript errors if `myPeerId` is the wrong type

**Closed by SgtPooki** 2024-09-20 14:23 UTC
Labels: need/community-input, exp/intermediate
