### ISSUE TITLE
30+ Broken links in readme.

### ISSUE THREAD

**Issue by MichaelJCole** [libp2p/js-libp2p#2423] opened 2024-02-24 16:49 UTC
- **Version**:
Current

- **Platform**:
Github

- **Subsystem**:
Documentation

#### Severity:
High?

#### Description:
Hi, thanks for this visionary project.  I noticed some links in the readme are broken.

See broken links in the attached file:
[libp2p.github.io.csv](https://github.com/libp2p/js-libp2p/files/14393634/libp2p.github.io.csv)
[libp2p.github.io.html.zip](https://github.com/libp2p/js-libp2p/files/14393651/libp2p.github.io.html.zip)

#### Steps to reproduce the error:
```
docker run --rm dcycle/broken-link-checker:3 -r 1 https://libp2p.github.io/js-libp2p/index.html  > ~/Desktop/libp2p.github.io.csv 
```

**Comment by achingbrain** [comment] 2024-03-11 10:35
Thanks for opening this - would you like to open a PR that updates the links to point to the new locations?

**Comment by MichaelJCole** [comment] 2024-03-13 02:28
Hi @achingbrain thank you responding.   How could I know *how* to do that?

I really have no idea how your project is structured or should be documented or how it works.  How could I know how it should work enough to document it?  

I wasted a bunch of time trying to customize Kubo only to realize it has 47 repos and doesn't make any sense.  I'm realizing libp2p and helia have the same problem.  

I've been filing bugs on js-store (https://github.com/ipfs/js-stores/issues/300 and https://github.com/ipfs/js-stores/issues/299).  I finally worked that out, but I burned a bunch of time on it.  I ran into problems with simple-metrics and didn't file issues.  I'm not sure what is supposed to work and what is abandoned. I can do drive-by contributions improving something that already exists.  I can make PR's if I know how it's supposed to work.

If yall are serious about inviting contributions, start with a README and documentation - I added the link checker so it should be a few minutes of work for someone who wrote it.  Otherwise, it just seems like a lazy request to spend hours cleaning up someone else's unfinished work.  I can't do that, I have to create value for my users.

**Comment by SgtPooki** [comment] 2024-04-12 21:06
I ran the docker broken link checker and checked into `GETTING_STARTED.md` broken link. it looks like `packages/libp2p/README.md` is linking to `./doc/GETTING_STARTED.md` which exists on the root. 

@achingbrain I think some of the doc building in [aegir](https://github.com/ipfs/aegir) isn't handling links to github docs properly. Also, looking at the output of `.docs` after building locally, it doesn't seem to contain any markdown files:

```
╰─ ✔ ❯ ls .docs
assets         classes        enums          functions      hierarchy.html index.html     interfaces     modules        types          variables


╰─ ✔ ❯ ls .docs/**/*.md
zsh: no matches found: .docs/**/*.md
```

@MichaelJCole for now, you should probably use links from the github README root cause those will resolve properly.

**Closed** 2024-04-23 10:27 UTC
Labels: need/triage
