### ISSUE TITLE
Discuss: "bundling" terminology is confusing

### ISSUE THREAD

**Issue by raulk** [libp2p/js-libp2p#350] opened 2019-04-08 10:39 UTC
The term "bundle" in modern Javascript land often implies things like packaging, minification, tree shaking, etc. all of which don't apply in our usage of the term. It evokes Webpack, Parcel, etc. I've received feedback from developers that this is confusing.

Really, what we are trying to recommend is putting libp2p imports and configuration in one file, and exporting it from there. Calling that a "bundle" is unnecessarily complex IMO.

Can we simplify this?

**Comment by raulk** [comment] 2019-04-08 10:40
cc @mikerah

**Comment by raulk** [comment] 2019-04-08 10:41
I actually think it's great to point to real examples of libp2p node configurations like the ones in IPFS. Can we point to other projects too?

**Comment by raulk** [comment] 2019-04-08 10:41
Alternatively we may want to bring in those examples into libp2p itself as "blueprints" or something.

**Comment by jacobheun** [comment] 2019-04-08 10:48
This is a duplicate of https://github.com/libp2p/js-libp2p/issues/231.

It would be ideal to do a full audit of the readme and language used, including bundling. There is an open issue at https://github.com/libp2p/js-libp2p/issues/237.

**Comment by raulk** [comment] 2019-04-08 11:05
@jacobheun gotcha, let's dislodge all this stuff! Should we create a `dx` label and group all these tasks and discussions so we can address them ASAP?

**Comment by jacobheun** [comment] 2019-04-08 11:18
@raulk yes, let's group them at https://github.com/libp2p/js-libp2p/issues/308 which is to track the OKR around improved docs and examples. I'll comment there with links to each of the issues for `js-libp2p` itself and tag each of those with the new label.

**Comment by yusefnapora** [comment] 2019-04-08 13:56
I agree that this is a confusing bit of terminology -  we should either publish common "bundles" as npm packages, or just get rid of the term entirely and refer to "configuring libp2p" instead as suggested [here](https://github.com/libp2p/js-libp2p/issues/231#issuecomment-410865609).

**Comment by Mikerah** [comment] 2019-04-10 03:31
I actually just got into this very issue a few days ago. I used the word __bundle__ in the same paragraph both in the JS sense and libp2p sense. A suggestion I have would just to refer to them as libp2p modules or libp2p configurations.

**Comment by vasco-santos** [comment] 2020-03-10 11:23
We got away of the `bundle` terminology on the latest release, as a consequence of it has been reported as confusing by several issues. Closing this as it is not relevant anymore

**Closed by vasco-santos** 2020-03-10 11:23 UTC
