### ISSUE TITLE
Error: MAC Invalid

### ISSUE THREAD

**Issue by alanshaw** [libp2p/js-libp2p#310] opened 2019-01-16 10:44 UTC
Seen in browser interop tests:

```console
  3) circuit,go-browser-browser
       connect:
     Error: MAC Invalid: 6d25aacf9886fba50acbf478c9b0b27d05e2bf658eeb6585a39b1bf0c22be69c != e9571ae1c7848c1fa4009a68518c8aef816a4648080378b393527305f4e18dc7
    at mac.digest (webpack://interopipfs/node_modules/libp2p-secio/src/etm.js:57 <- test/browser.js:147547:21)
    at promise.then (webpack://interopipfs/node_modules/libp2p-crypto/src/nodeify.js:7 <- test/browser.js:137566:5)
```

**Comment by vasco-santos** [comment] 2020-03-10 11:13
I haven't seen this error for a long time. Any updates?

**Comment by achingbrain** [comment] 2020-03-11 07:12
Running under electron-renderer on travis just now:

```
ipfs:     Error: MAC Invalid: c2735d9cfb004ad80eaf50901aea8b1e96f3e29459a412a2481c74d6210c1ada != 2d04f3aa54a5f5c77232dc3db72bfdaff2fa013f134b249159767fced80ef38b
ipfs:         at /Users/travis/build/ipfs/js-ipfs/node_modules/libp2p-secio/src/etm.js:33:15
ipfs:       at errorHandler (/Users/travis/build/ipfs/js-ipfs/packages/ipfs-http-client/src/lib/error-handler.js:41:17)
ipfs:       at async fn (/Users/travis/build/ipfs/js-ipfs/node_modules/ky/umd.js:325:31)
ipfs:       at async Promise.Ky.result.<computed> [as json] (/Users/travis/build/ipfs/js-ipfs/node_modules/ky/umd.js:363:14)
ipfs:       at async Object.connect (/Users/travis/build/ipfs/js-ipfs/packages/ipfs-http-client/src/swarm/connect.js:13:17)
ipfs:       at async Object.connect (/Users/travis/build/ipfs/js-ipfs/packages/ipfs/node_modules/ipfs-interop/test/utils/circuit.js:130:3)
```

**Comment by jacobheun** [comment] 2020-03-11 12:24
related to https://github.com/libp2p/js-libp2p-secio/issues/116.

**Comment by achingbrain** [comment] 2020-03-13 18:18
Not sure how useful it is me reporting the frequency, but it happened again.

**Comment by jacobheun** [comment] 2020-03-13 18:37
@achingbrain was that also in the circuit tests? If the stack traces are different that would be helpful. While they're not very informative we can try and narrow down specific test areas to stress test to find the root problem.

**Comment by achingbrain** [comment] 2020-03-13 19:47
It was, yes.  I'll post a stack trace next time it happens.

**Comment by achingbrain** [comment] 2020-03-19 19:52
```
ipfs:   1) circuit
ipfs:        js-go-go
ipfs:          connect:
ipfs:      HTTPError: 
ipfs:     Error: MAC Invalid: 19447deda3dd195c1142fb7459b13e492653349522dc9cb067b9b0656eef7385 != 64385ccaabe025477158694fcb09cacb3f2fdedc617684cdd64b0859c6bdb9e8
ipfs:         at /Users/travis/build/ipfs/js-ipfs/node_modules/libp2p-secio/src/etm.js:33:15
ipfs:       at Object.errorHandler [as handleError] (/Users/travis/build/ipfs/js-ipfs/packages/ipfs-http-client/src/lib/core.js:66:17)
ipfs:       at processTicksAndRejections (internal/process/task_queues.js:89:5)
ipfs:       at async Client.fetch (/Users/travis/build/ipfs/js-ipfs/packages/ipfs-utils/src/http.js:135:9)
ipfs:       at async Object.connect (/Users/travis/build/ipfs/js-ipfs/packages/ipfs-http-client/src/swarm/connect.js:12:24)
ipfs:       at async Object.connect (/Users/travis/build/ipfs/js-ipfs/packages/ipfs/node_modules/ipfs-interop/test/utils/circuit.js:134:3)
```

**Comment by achingbrain** [comment] 2020-03-24 20:49
```
ipfs:   1) circuit
189ipfs:        js-go-go
190ipfs:          connect:
191ipfs:      HTTPError: 
192ipfs:     Error: MAC Invalid: 876418412351125d61cd313d8ed98ad8166afa23e29a40f35e8b08589bc512a6 != 03378eac9d646bd1bfcb71d9e3184a385bf11fe53354d65789c372615b1af12b
193ipfs:         at /Users/travis/build/ipfs/js-ipfs/node_modules/libp2p-secio/src/etm.js:33:15
194ipfs:       at Object.errorHandler [as handleError] (/Users/travis/build/ipfs/js-ipfs/packages/ipfs-http-client/src/lib/core.js:66:17)
195ipfs:       at processTicksAndRejections (internal/process/task_queues.js:89:5)
196ipfs:       at async Client.fetch (/Users/travis/build/ipfs/js-ipfs/node_modules/ipfs-utils/src/http.js:135:9)
197ipfs:       at async Object.connect (/Users/travis/build/ipfs/js-ipfs/packages/ipfs-http-client/src/swarm/connect.js:12:24)
198ipfs:       at async Object.connect (/Users/travis/build/ipfs/js-ipfs/packages/ipfs/node_modules/ipfs-interop/test/utils/circuit.js:134:3)
199ipfs: 
200ipfs: Command failed: electron-mocha ./test/browser.js --log-level error --bail true --timeout true --colors --renderer
201ipfs: npm ERR! Test failed.  See above for more details.
202ipfs: /Users/travis/build/ipfs/js-ipfs/packages/ipfs/node_modules/ipfs-interop/bin/ipfs-interop.js:15
203ipfs:     throw new Error(`Child process exited with code ${code}`)
204ipfs:     ^
205ipfs: Error: Child process exited with code 1
206ipfs:     at ChildProcess.proc.on (/Users/travis/build/ipfs/js-ipfs/packages/ipfs/node_modules/ipfs-interop/bin/ipfs-interop.js:15:11)
207ipfs:     at ChildProcess.emit (events.js:198:13)
208ipfs:     at maybeClose (internal/child_process.js:982:16)
209ipfs:     at Socket.stream.socket.on (internal/child_process.js:389:11)
210ipfs:     at Socket.emit (events.js:198:13)
211ipfs:     at Pipe._handle.close (net.js:607:12)
212ipfs: npm ERR! code ELIFECYCLE
213ipfs: npm ERR! errno 1
214ipfs: npm ERR! ipfs@0.41.2 test:interop:electron-renderer: `cross-env IPFS_JS_EXEC=$PWD/src/cli/bin.js IPFS_JS_MODULE=$PWD IPFS_REUSEPORT=false ipfs-interop -- -t electron-renderer -f ./test/browser.js "--bail" "--timeout" "10000"`
215ipfs: npm ERR! Exit status 1
216ipfs: npm ERR! 
217ipfs: npm ERR! Failed at the ipfs@0.41.2 test:interop:electron-renderer script.
```

**Comment by achingbrain** [comment] 2020-03-26 11:57
```
ipfs:   1) circuit
ipfs:        js-go-go
ipfs:          connect:
ipfs:      HTTPError: 
ipfs:     Error: MAC Invalid: e6729a901237231381d846bbeea35eca1de946ead90e88291a06b7ef3d8139a5 != 7b2b32eebb510afb16936301558b43fd7c00ad705952302fb503c6e949a451a5
ipfs:         at /Users/travis/build/ipfs/js-ipfs/node_modules/libp2p-secio/src/etm.js:33:15
ipfs:       at Object.errorHandler [as handleError] (/Users/travis/build/ipfs/js-ipfs/packages/ipfs-http-client/src/lib/core.js:66:17)
ipfs:       at async Client.fetch (/Users/travis/build/ipfs/js-ipfs/node_modules/ipfs-utils/src/http.js:135:9)
ipfs:       at async Object.connect (/Users/travis/build/ipfs/js-ipfs/packages/ipfs-http-client/src/swarm/connect.js:12:24)
ipfs:       at async Object.connect (/Users/travis/build/ipfs/js-ipfs/packages/ipfs/node_modules/ipfs-interop/test/utils/circuit.js:134:3)
ipfs: 
ipfs: Command failed with exit code 1: electron-mocha ./test/node.js --log-level error --bail true --timeout true --colors --full-trace
ipfs: npm ERR! Test failed.  See above for more details.
ipfs: /Users/travis/build/ipfs/js-ipfs/packages/ipfs/node_modules/ipfs-interop/bin/ipfs-interop.js:15
ipfs:     throw new Error(`Child process exited with code ${code}`)
ipfs:     ^
ipfs: Error: Child process exited with code 1
ipfs:     at ChildProcess.proc.on (/Users/travis/build/ipfs/js-ipfs/packages/ipfs/node_modules/ipfs-interop/bin/ipfs-interop.js:15:11)
ipfs:     at ChildProcess.emit (events.js:198:13)
ipfs:     at maybeClose (internal/child_process.js:982:16)
ipfs:     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Comment by jacobheun** [comment] 2020-03-26 12:45
I think we're good on stack traces unless they come from somewhere else than circuit relay. They all look like they're coming from `swarm connect` so we should be able to focus testing around interop circuit connection establishment scenarios.

**Comment by achingbrain** [comment] 2020-04-24 14:07
This is still happening.

**Comment by jacobheun** [comment] 2020-04-24 14:13
I'll be working on crypto stuff the next couple of weeks to get Noise and ed25519 support in js-ipfs in preparation for the go-ipfs 0.6 release in June, so I will investigate this.

As a note, Secio is also slated to be deprecated around the end of July (go-ipfs 0.7). I still want to figure out the root cause here as part of this effort as we don't know where the actual issue is at this point.

**Comment by jacobheun** [comment] 2021-02-26 13:41
This came from Secio which has been deprecated in favor of Noise, closing this.

**Closed by jacobheun** 2021-02-26 13:41 UTC
Labels: P2 - Medium, bug, difficulty:hard, ready
