### ISSUE TITLE
Discovery mechanisms example: Pubsub-Peer-Discovery not discovering peers.

### ISSUE THREAD

**Issue by sneaker1** [libp2p/js-libp2p#1229] opened 2022-05-26 20:39 UTC
In the discovery mechanism example Part 3 Pubsub based Peer Discovery is a problem.

https://github.com/libp2p/js-libp2p/tree/master/examples/discovery-mechanisms#3-pubsub-based-peer-discovery

If i run the 3.js i can not discover other peers. 
Here is my output:
```sh
> node 3.js
libp2p relay starting with id: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Node 0 starting with id: 12D3KooWSiExtrTywWfj3xoFFqSPV7kJqwkBQaxJuwB4m9BEntQg
Node 1 starting with id: 12D3KooWDgxwvf5p6BCmyYL3Srzff9FhPWLGJeq7w97d4nsERfFm
Peer 12D3KooWSiExtrTywWfj3xoFFqSPV7kJqwkBQaxJuwB4m9BEntQg discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWSiExtrTywWfj3xoFFqSPV7kJqwkBQaxJuwB4m9BEntQg discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWDgxwvf5p6BCmyYL3Srzff9FhPWLGJeq7w97d4nsERfFm discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWDgxwvf5p6BCmyYL3Srzff9FhPWLGJeq7w97d4nsERfFm discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWSiExtrTywWfj3xoFFqSPV7kJqwkBQaxJuwB4m9BEntQg discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWDgxwvf5p6BCmyYL3Srzff9FhPWLGJeq7w97d4nsERfFm discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWSiExtrTywWfj3xoFFqSPV7kJqwkBQaxJuwB4m9BEntQg discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWDgxwvf5p6BCmyYL3Srzff9FhPWLGJeq7w97d4nsERfFm discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWSiExtrTywWfj3xoFFqSPV7kJqwkBQaxJuwB4m9BEntQg discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWSiExtrTywWfj3xoFFqSPV7kJqwkBQaxJuwB4m9BEntQg discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWSiExtrTywWfj3xoFFqSPV7kJqwkBQaxJuwB4m9BEntQg discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWSiExtrTywWfj3xoFFqSPV7kJqwkBQaxJuwB4m9BEntQg discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWDgxwvf5p6BCmyYL3Srzff9FhPWLGJeq7w97d4nsERfFm discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWDgxwvf5p6BCmyYL3Srzff9FhPWLGJeq7w97d4nsERfFm discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWDgxwvf5p6BCmyYL3Srzff9FhPWLGJeq7w97d4nsERfFm discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWDgxwvf5p6BCmyYL3Srzff9FhPWLGJeq7w97d4nsERfFm discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWSiExtrTywWfj3xoFFqSPV7kJqwkBQaxJuwB4m9BEntQg discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWSiExtrTywWfj3xoFFqSPV7kJqwkBQaxJuwB4m9BEntQg discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWDgxwvf5p6BCmyYL3Srzff9FhPWLGJeq7w97d4nsERfFm discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
Peer 12D3KooWDgxwvf5p6BCmyYL3Srzff9FhPWLGJeq7w97d4nsERfFm discovered: 12D3KooWNZcrYfNvQ5kkbMZnPJVwQ28R4LkdH34pJsDuUFMWpXg3
```
As you can see only the bootstrap peer-id is discovered. 
The peer-ids of node 0 and node 1 are not discovered.

According to the example the output should be like this. (Node 0 and Node 1 are discovered)
```sh
> node 3.js
libp2p relay starting with id: QmW6FqVV6RsyoGC5zaeFGW9gSWA3LcBRVZrjkKMruh38Bo
Node 0 starting with id: QmezqDTmEjZ5BfMgVqjSpLY19mVVLTQ9bE9mRpZwtGxL8N
Node 1 starting with id: QmYWeom2odTkm79DzB68NHULqVHDaNDqHhoyqLdcV1fqdv
Peer QmezqDTmEjZ5BfMgVqjSpLY19mVVLTQ9bE9mRpZwtGxL8N discovered: QmW6FqVV6RsyoGC5zaeFGW9gSWA3LcBRVZrjkKMruh38Bo
Peer QmYWeom2odTkm79DzB68NHULqVHDaNDqHhoyqLdcV1fqdv discovered: QmW6FqVV6RsyoGC5zaeFGW9gSWA3LcBRVZrjkKMruh38Bo
Peer QmYWeom2odTkm79DzB68NHULqVHDaNDqHhoyqLdcV1fqdv discovered: QmezqDTmEjZ5BfMgVqjSpLY19mVVLTQ9bE9mRpZwtGxL8N
Peer QmezqDTmEjZ5BfMgVqjSpLY19mVVLTQ9bE9mRpZwtGxL8N discovered: QmYWeom2odTkm79DzB68NHULqVHDaNDqHhoyqLdcV1fqdv
```

I assume the example has worked before. So maybe there is a problem in the current versions of libp2p.

I am running the most recent versions. Here are the dependencies from my package.json:
```json
"dependencies": {
  "@chainsafe/libp2p-noise": "^6.2.0",
  "@libp2p/bootstrap": "^1.0.6",
  "@libp2p/floodsub": "^1.0.7",
  "@libp2p/mplex": "^1.1.0",
  "@libp2p/pubsub-peer-discovery": "^5.0.4",
  "@libp2p/tcp": "^1.0.11",
  "libp2p": "^0.37.1"
}
```

**Comment by sethhrbek** [comment] 2022-06-10 18:14
I believe the issue is that the `broadcast` function is publishing a message in a different format than `onMessage` is expecting to receive.

In versions prior to 5 (>= 4), `broadcast` was broadcasting via:
`publish(topic, encodedPeer)` 

As of version 5 it is doing:
```
pubsub.dispatchEvent(new CustomEvent('message', {
  detail: encodedPeer
}))
```

`onMessage` has signature:
`  _onMessage (event: CustomEvent<Message>)`

And `Message` interface is:

```
export interface Message {
  from: PeerId
  topic: string
  data: Uint8Array
  sequenceNumber?: bigint
  signature?: Uint8Array
  key?: Uint8Array
}
```

**Comment by mpetrunic** [comment] 2022-08-30 16:01
@sneaker1 We think it's fixed in the latest libp2p version, can you try using latest version?

**Comment by zargarzadehm** [comment] 2022-08-30 21:55
> @sneaker1 We think it's fixed in the latest libp2p version, can you try using latest version?

 I tested that but exist this problem yet :((

```
➜  discovery-mechanisms git:(master) ✗ node 3.js
libp2p relay starting with id: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Node 0 starting with id: 12D3KooWMVc4etyuv1A15Dx6dmdNEeTDYY2vmRZuutXGQZ23x1Gi
Node 1 starting with id: 12D3KooWETSnb9tsdE9SkJ2BLY7JveFD9YLRiXUq7m6X1eGjk8NS
Peer 12D3KooWMVc4etyuv1A15Dx6dmdNEeTDYY2vmRZuutXGQZ23x1Gi discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWMVc4etyuv1A15Dx6dmdNEeTDYY2vmRZuutXGQZ23x1Gi discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWMVc4etyuv1A15Dx6dmdNEeTDYY2vmRZuutXGQZ23x1Gi discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWETSnb9tsdE9SkJ2BLY7JveFD9YLRiXUq7m6X1eGjk8NS discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWETSnb9tsdE9SkJ2BLY7JveFD9YLRiXUq7m6X1eGjk8NS discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWETSnb9tsdE9SkJ2BLY7JveFD9YLRiXUq7m6X1eGjk8NS discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWMVc4etyuv1A15Dx6dmdNEeTDYY2vmRZuutXGQZ23x1Gi discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWMVc4etyuv1A15Dx6dmdNEeTDYY2vmRZuutXGQZ23x1Gi discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWETSnb9tsdE9SkJ2BLY7JveFD9YLRiXUq7m6X1eGjk8NS discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWETSnb9tsdE9SkJ2BLY7JveFD9YLRiXUq7m6X1eGjk8NS discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWMVc4etyuv1A15Dx6dmdNEeTDYY2vmRZuutXGQZ23x1Gi discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWMVc4etyuv1A15Dx6dmdNEeTDYY2vmRZuutXGQZ23x1Gi discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWMVc4etyuv1A15Dx6dmdNEeTDYY2vmRZuutXGQZ23x1Gi discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWMVc4etyuv1A15Dx6dmdNEeTDYY2vmRZuutXGQZ23x1Gi discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWMVc4etyuv1A15Dx6dmdNEeTDYY2vmRZuutXGQZ23x1Gi discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWMVc4etyuv1A15Dx6dmdNEeTDYY2vmRZuutXGQZ23x1Gi discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWETSnb9tsdE9SkJ2BLY7JveFD9YLRiXUq7m6X1eGjk8NS discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR
Peer 12D3KooWETSnb9tsdE9SkJ2BLY7JveFD9YLRiXUq7m6X1eGjk8NS discovered: 12D3KooWQ6RS7HuSsfwpuYeskzjhTpg4Q61Rstw5MCmEQcwAaLAR

```

I am running the most recent versions. Here are the dependencies from my package.json:

```json
  "dependencies": {
    "@chainsafe/libp2p-noise": "^8.0.1",
    "@libp2p/bootstrap": "^2.0.0",
    "@libp2p/floodsub": "^3.0.5",
    "@libp2p/mplex": "^5.0.0",
    "@libp2p/pubsub-peer-discovery": "^6.0.1",
    "@libp2p/tcp": "^3.0.4",
    "execa": "^6.1.0",
    "libp2p": "0.38.0",
    "p-defer": "^4.0.0",
    "uint8arrays": "^3.1.0"
  }

```

**Closed** 2022-09-05 14:17 UTC
Labels: kind/bug
