### ISSUE TITLE
Inconsistency between implementations on connect

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#327] opened 2019-02-19 15:20 UTC
- **Version**: 0.25.0-rc.0
- **Platform**: Mac os
- **Subsystem**: Dial

#### Description:

In the context of creating interop tests for guaranteeing that peers implemented in a specific language are able to connect with other nodes, regardless of their implementation language, I found out a different behavior when connecting two JS nodes.

Connecting JS -> Go, Go -> JS and Go -> Go all work fine. However, when connecting JS A -> JS B, JS B takes some time to have its known peers updated.

Testing: https://github.com/libp2p/interop/pull/4/files#diff-cfbb48e0364acbf79524761f7b1b125fR53

**Comment by achingbrain** [comment] 2022-10-05 16:14
Closing as complete - please re-open if the problem is still observed

**Closed by achingbrain** 2022-10-05 16:14 UTC
Labels: kind/bug, exp/expert, status/ready, P2
