### ISSUE TITLE
Peer keeps reconnecting every ~30 seconds.

### ISSUE THREAD

**Issue by AlexMesser** [libp2p/js-libp2p#1513] opened 2022-12-06 13:23 UTC
- **Version**: 0.40.0

- **Platform**: macOS 12.5

- **Subsystem**: Connection Manager

#### Description:

I have two peers connected to the same relay server. Peers successfully connect to each other, but keep reconnecting every ~30 seconds being unreachable for 80-100ms. Since we are heavily using pubsub in our app, this behavior leads to missing pubsub messages in this reconnection intervals.

I put some logs on `connect/disconnect` events on both peers:

```ts
    // Listen for new connections to peers
    libp2p.connectionManager.addEventListener("peer:connect", async (evt) => {
      const connection = evt.detail
      console.log(`Connected to ${connection.remotePeer.toString()}`)
      console.time("disconnected after")
      console.timeEnd("reconnected after")
    })

    // Listen for peers disconnecting
    libp2p.connectionManager.addEventListener("peer:disconnect", (evt) => {
      const connection = evt.detail
      console.log(`Disconnected from ${connection.remotePeer.toString()}`)
      console.timeEnd("disconnected after")
      console.time("reconnected after")
    })
```

**Relay logs:**

```shell
----------------------------------------------
PeerId: 12D3KooWNvSZnPi3RrhrTwEY4LuuBeB6K6facKUCJcyWG1aoDd2p
Listening on: [
  '/ip4/127.0.0.1/tcp/5001/p2p/12D3KooWNvSZnPi3RrhrTwEY4LuuBeB6K6facKUCJcyWG1aoDd2p',
  '/ip4/192.168.68.115/tcp/5001/p2p/12D3KooWNvSZnPi3RrhrTwEY4LuuBeB6K6facKUCJcyWG1aoDd2p'
]
----------------------------------------------
Connected to 12D3KooWLV3w42LqUb9MWE7oTzG7vwaFjPw9GvDqmsuDif5chTn9
Connected to 12D3KooWFYyvJysHGbbYiruVY8bgjKn7sYN9axgbnMxrWVkGXABF
```

**Peer A:**

```shell
----------------------------------------------
PeerId: 12D3KooWLV3w42LqUb9MWE7oTzG7vwaFjPw9GvDqmsuDif5chTn9
Listening on: [
  '/ip4/127.0.0.1/tcp/5001/p2p/12D3KooWNvSZnPi3RrhrTwEY4LuuBeB6K6facKUCJcyWG1aoDd2p/p2p-circuit/p2p/12D3KooWLV3w42LqUb9MWE7oTzG7vwaFjPw9GvDqmsuDif5chTn9'
]
----------------------------------------------
Connected to 12D3KooWFYyvJysHGbbYiruVY8bgjKn7sYN9axgbnMxrWVkGXABF
Disconnected from 12D3KooWFYyvJysHGbbYiruVY8bgjKn7sYN9axgbnMxrWVkGXABF
disconnected after: 29.925s
Connected to 12D3KooWFYyvJysHGbbYiruVY8bgjKn7sYN9axgbnMxrWVkGXABF
reconnected after: 99.658ms
Disconnected from 12D3KooWFYyvJysHGbbYiruVY8bgjKn7sYN9axgbnMxrWVkGXABF
disconnected after: 29.954s
Connected to 12D3KooWFYyvJysHGbbYiruVY8bgjKn7sYN9axgbnMxrWVkGXABF
reconnected after: 89.978ms
Disconnected from 12D3KooWFYyvJysHGbbYiruVY8bgjKn7sYN9axgbnMxrWVkGXABF
disconnected after: 29.968s
Connected to 12D3KooWFYyvJysHGbbYiruVY8bgjKn7sYN9axgbnMxrWVkGXABF
reconnected after: 85.511ms
Disconnected from 12D3KooWFYyvJysHGbbYiruVY8bgjKn7sYN9axgbnMxrWVkGXABF
disconnected after: 29.963s
```

**Peer B:**

```shell
----------------------------------------------
PeerId: 12D3KooWFYyvJysHGbbYiruVY8bgjKn7sYN9axgbnMxrWVkGXABF
Listening on: [
  '/ip4/127.0.0.1/tcp/5001/p2p/12D3KooWNvSZnPi3RrhrTwEY4LuuBeB6K6facKUCJcyWG1aoDd2p/p2p-circuit/p2p/12D3KooWFYyvJysHGbbYiruVY8bgjKn7sYN9axgbnMxrWVkGXABF'
]
----------------------------------------------
Connected to 12D3KooWLV3w42LqUb9MWE7oTzG7vwaFjPw9GvDqmsuDif5chTn9
Disconnected from 12D3KooWLV3w42LqUb9MWE7oTzG7vwaFjPw9GvDqmsuDif5chTn9
reconnected after: 29.937s
Connected to 12D3KooWLV3w42LqUb9MWE7oTzG7vwaFjPw9GvDqmsuDif5chTn9
unavailable for: 127.696ms
Disconnected from 12D3KooWLV3w42LqUb9MWE7oTzG7vwaFjPw9GvDqmsuDif5chTn9
reconnected after: 29.960s
Connected to 12D3KooWLV3w42LqUb9MWE7oTzG7vwaFjPw9GvDqmsuDif5chTn9
unavailable for: 89.762ms
Disconnected from 12D3KooWLV3w42LqUb9MWE7oTzG7vwaFjPw9GvDqmsuDif5chTn9
reconnected after: 29.967s
Connected to 12D3KooWLV3w42LqUb9MWE7oTzG7vwaFjPw9GvDqmsuDif5chTn9
unavailable for: 78.319ms
Disconnected from 12D3KooWLV3w42LqUb9MWE7oTzG7vwaFjPw9GvDqmsuDif5chTn9
reconnected after: 29.969s
```

I tested the same behavior on go-libp2p nodes and there were no reconnects during the node lifecycle.

Is this a bug or by design or is it configurable somehow?

**Comment by AlexMesser** [comment] 2022-12-08 16:27
@achingbrain sure, [here it is](https://github.com/AlexMesser/peer-reconnect-reproduction)

**Comment by sadeghte** [comment] 2022-12-30 23:46
Same problem !!
Any progress ?

**Comment by bakhshandeh** [comment] 2023-01-03 07:34
It seems that the issue is on libp2p-tcp package.
https://github.com/libp2p/js-libp2p-tcp/blob/92e144211784bb9c21f799c4c5fcab9c72ef5d8a/src/socket-to-conn.ts#L64
`inactivityTimeout` is 30 seconds by default and the sockets will be closed after that.
This lib2p2 config disables timeout and fixes the issue:

```javascript

transports: [tcp({
  	outboundSocketInactivityTimeout: 0
})]
```

It disabling the timeout safe?

**Comment by achingbrain** [comment] 2023-01-03 17:05
> It disabling the timeout safe?

If the default in node is to not have a timeout, then maybe?  It's possible the [default timeout](https://github.com/libp2p/js-libp2p-tcp/blob/92e144211784bb9c21f799c4c5fcab9c72ef5d8a/src/constants.ts#L10) is too short - the solution might be to have no timeout by default (e.g the same as node) and let people configure it if they need it.

Please can you open an issue against [libp2p/js-libp2p-tcp](https://github.com/libp2p/js-libp2p-tcp) to discuss this?

Closing as the solution is to disable the timeout.

**Closed by achingbrain** 2023-01-03 17:05 UTC
Labels: need/triage

**Comment by sneaker1** [comment] 2023-01-28 17:17
I am having the same issue.
The problem exists with tcp as well as with websockets.
I also tried to manually set the timeout to 0 as mentioned above. But this didn't help.
