### ISSUE TITLE
refactor: move protocols out of libp2p package

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p#2102] opened 2023-10-02 18:40 UTC
Currently, the `libp2p` package is bloated by lots of functionality that should be moved to new monorepo packages

- autonat
- circuit-relay
- dcutr
- fetch
- identify
- insecure
- ping
- pnet
- upnp-nat

**Comment by maschad** [comment] 2023-10-02 22:18
Nice, I just found that this was a duplicate of https://github.com/libp2p/js-libp2p/issues/1913

**Closed by maschad** 2023-10-02 22:18 UTC
Labels: need/triage
