### ISSUE TITLE
Transfer times got twice longer between js-libp2p@0.36.2 and js-libp2p@0.37.3

### ISSUE THREAD

**Issue by Alexis-ROYER** [libp2p/js-libp2p#1342] opened 2022-08-11 18:19 UTC
- **Version**: js-libp2p@0.36.2 and js-libp2p@0.37.3
- **Platform**: Windows + node v16.13.2
- **Subsystem**: (to be identified)

#### Severity:

Medium (performance issue)

#### Description:

According to my experimentations, transfer times got twice longer between js-libp2p@0.36.2 and js-libp2p@0.37.3.

If I am true:
- Is the reason known for it? (additional features? refactorings? ...)
- What is the priority for the libp2p team to address this kind of issue?

#### Steps to reproduce the error:

See the following test scripts (one for each version of js-libp2p):
- [libp2p-node.0.36.x.cjs](https://github.com/libp2p/js-libp2p/files/9310751/libp2p-node.0.36.x.cjs.txt)
- [libp2p-node.0.37.x.mjs](https://github.com/libp2p/js-libp2p/files/9310753/libp2p-node.0.37.x.mjs.txt)

Those scripts make it possible to launch 2 nodes:
- a sender, with the following options:
    - `--send`: path to a file which data to send,
    - `--size`: size of the chunks for sending the data.
- a receiver, with the following options:
    - `--connect` option set with the address printed out by the sender.

Timestamps are printed out when the sender starts sending the data, and when the receiver has finished receiving all of it.

With a bit of scripting around it, I made up the following graphs:

![p2p901-2022-08-08a](https://user-images.githubusercontent.com/41943581/184196445-0a20d6de-8ce5-4612-a5f3-6a284554899a.png)
Note: Chunks of 100 bytes are not representative in as much as it causes a lot of overhead around the useful data actually transfered (see [#1343](https://github.com/libp2p/js-libp2p/issues/1343#issuecomment-1212373444)).

![p2p901-2022-08-08b](https://user-images.githubusercontent.com/41943581/184196508-e83b2d04-bc84-4049-87fa-538a9bc8e3c5.png)

![p2p901-2022-08-08c](https://user-images.githubusercontent.com/41943581/184196547-388f3bce-daa0-4c71-a163-40e21557d370.png)

As the graphs show it, js-libp2p@0.37.3 transfer times are about twice those of js-libp2p@0.36.2 from chunk sizes of 1Kb.

**Comment by Alexis-ROYER** [comment] 2022-08-11 18:28
Possibly related to #1303.

**Comment by wemeetagain** [comment] 2022-08-11 20:17
@Alexis-ROYER having not looked at your case specifically, so I can't say 100% that the problem is #1303 but its very likely most of it is.
Other notable regression is protobuf encoders/decoders.

We're actively working on resolving the performance issues, and most of the work has landed in our nightly version. This is our current focus (along with stabilizing the types) before pushing out a v0.38.0.

**Comment by mpetrunic** [comment] 2022-08-30 15:49
@Alexis-ROYER Could you try with the latest 0.38 version?

**Comment by achingbrain** [comment] 2022-09-06 15:29
Closing as the issue should be resolved - please re-open if you continue to observe it.

**Comment by Alexis-ROYER** [comment] 2022-09-09 21:55
I've updated my measures with js-libp2p@0.38.0 and js-libp2p@0.39.0:
![p2p901-2022-09-09b](https://user-images.githubusercontent.com/41943581/189450866-9aee83c6-a64b-4d1c-b5c9-22d7e3331146.png)
![p2p901-2022-09-09c](https://user-images.githubusercontent.com/41943581/189450876-00e35780-8ddb-45f3-b8f0-098e163f96b8.png)

Transfer times are still about those of js-libp2p@0.37.3, higher than js-libp2p@0.36.2.

**Comment by Alexis-ROYER** [comment] 2022-09-09 21:58
@achingbrain Could you please re-open the issue? I can't on my side.

**Comment by achingbrain** [comment] 2022-09-12 12:29
I've put a test bed together here: https://github.com/ipfs-shipyard/js-libp2p-transfer-performance

It takes a slightly different approach to the two files in the OP - notably it doesn't configure a DHT since it's not needed and uses the plaintext connection encrypter instead of noise as it's simpler.

It transfers 100MiB of data between the two nodes using increasing chunk sizes, recording how long it takes.

Since the thing doing all the work here is the stream multiplexer, it tests `0.36.x`, `0.37.x`, `0.38.x` and `0.39.x` with mplex and also `0.39.x` with the brand-new yamux multiplexer.  `0.38.x` and `0.39.x` use the same version of `@libp2p/mplex` so you'd expect their speeds to be comparable.

What I've found largely tallies with @Alexis-ROYER's investigation:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/665810/189650793-ad2388a4-e8f9-4bde-a727-8cc6a41122d3.png">

In the graph above I've ignored message sizes below 256b as I don't think many protocols would send messages so small but the values follow the general pattern.

`0.36.x` is definitely faster with small message sizes but that gets less pronounced as they increase in size - performance starts to coalesce at message sizes around 32kb.

We should look at the performance overhead for messages smaller than this to try to bring the gap down between the blue and green lines in the graph above.

Other takeaways are that if you're using `0.37.x` you should upgrade to `0.38.x` or later and yamux can probably be optimised somewhat (not a criticism, it's still very new).

**Comment by mpetrunic** [comment] 2022-09-12 13:08
I will run some.profilling tools today to see what the hot paths are

**Comment by BigLep** [comment] 2022-09-13 15:39
2022-09-13 converation: @mpetrunic has done some profiling but libp2p dependencies aren't showing up with clinic.

@Alexis-ROYER: thanks for reporting this as clearly there is an issue.  We're curious how you noticed this and if this is having an impact on any applications/uses you have with js-libp2p.  This will help us gage where to prioritize this work.  And certainly any help digging into the issue is welcome.

**Comment by Alexis-ROYER** [comment] 2022-09-16 11:48
@BigLep My pleasure.

I was actually investigating on performance issues of an app I'm working on.
Among others, I'm tunnelling other protocols inside a libp2p connection between two peers.
Since it's a tunnelling process, chunks of data are those of the embedded protocols, which are about 5-10kB.

With some big data to transfer, things got stuck in while with libp2p@0.36.2.
When I upgraded with libp2p@0.37.3, things seemed to get more stable, but still slow.
In a dichotomic approach I started with qualifying transfer rate capabilities of libp2p out of my own code, which led me to report this issue.

**Comment by BigLep** [comment] 2022-09-23 07:02
I removed the relevant labels so this doesn't get auto closed.

**Comment by achingbrain** [comment] 2022-09-23 19:19
What I have found is that between `0.36.x` and `0.37.x` we have started sending about twice as many chunks of data as before.

In mplex we yield every encoded Uint8Array - in the current release that's [one for the header](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/encode.ts#L46) and [one (or more) for the data](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/encode.ts#L47), the theory being if you pump data into the socket opened by `@libp2p/tcp` as quickly as possible, the OS will figure out the best way to send the data. Turns out it's not quite that clever.

I have refactored this code locally to only ever yield one Uint8Array and the time taken to send 105MB of data in 256b chunks decreases from about 6s to about 3s, which is good but `0.36.x` is just under 2s so there's still a way to go.

Digging further, `0.36.x` sends chunks of data that are ~5xx bytes in one go - this is because the [array of messages that are encoded](https://github.com/libp2p/js-libp2p-mplex/blob/fc7e3a817e931b486c4a4dd61927374cb931f08c/src/coder/encode.js#L50) always has 2x members so they are encoded and transmitted at once.

`0.37.x`+ only ever has 1x member [in the same array at the same point](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/encode.ts#L66) - I have a local refactor that concatenates all the buffers together in the same way as `0.36.x` but it doesn't make much difference because there's still only ever one message.

The messages are added to [this pushableV](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/mplex.ts#L237-L240) but only ever [one at at time](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/mplex.ts#L177).

I've yet to ascertain why the older version yields 2x messages in one go - in theory the `pushable` will buffer input if it's not being consumed quickly enough - indeed adding an artificial delay to the newer code in the loop can cause multiple messages to be yielded which does increase performance a bit more but it's not much of a solution.

Once I figure out why the messages don't stack in recent releases the same way they do in `0.36.x` it opens up more possibilities - what if we send  more than 2x messages at once, could it be even faster?

I need to stop now but I'll keep digging on Monday.

**Comment by achingbrain** [comment] 2022-11-23 18:55
Good news, with #1491 and libp2p/js-libp2p-mplex#233 both applied streaming performance is fixed, not only that but it's now faster than `libp2p@0.36.x` with smaller message sizes for both mplex and yamux.  This will be all be in the next release.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/665810/203625536-6941b3fb-cff5-4ba7-978b-4d524c7b38bc.png">

**Closed** 2022-11-24 10:04 UTC
Labels: kind/bug, P2
