### ISSUE TITLE
Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by alanshaw** [libp2p/js-libp2p#374] opened 2019-06-28 12:51 UTC
Observed after running a daemon for a while:

```console
$ ipfs daemon
Initializing IPFS daemon...
js-ipfs version: 0.36.4
System version: x64/darwin
Node.js version: 12.2.0
Swarm listening on /ip4/0.0.0.0/tcp/4001/ipfs/QmNfRMVp4GDBjeGgT2sVmzG19CX4oDhs6oNdWS8R4djcZ7
Swarm listening on /ip6/::/tcp/4001/ipfs/QmNfRMVp4GDBjeGgT2sVmzG19CX4oDhs6oNdWS8R4djcZ7
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmNfRMVp4GDBjeGgT2sVmzG19CX4oDhs6oNdWS8R4djcZ7
Swarm listening on /p2p-circuit/ipfs/QmNfRMVp4GDBjeGgT2sVmzG19CX4oDhs6oNdWS8R4djcZ7
Swarm listening on /p2p-circuit/ip4/0.0.0.0/tcp/4001/ipfs/QmNfRMVp4GDBjeGgT2sVmzG19CX4oDhs6oNdWS8R4djcZ7
Swarm listening on /p2p-circuit/ip6/::/tcp/4001/ipfs/QmNfRMVp4GDBjeGgT2sVmzG19CX4oDhs6oNdWS8R4djcZ7
Swarm listening on /p2p-circuit/ip4/127.0.0.1/tcp/4003/ws/ipfs/QmNfRMVp4GDBjeGgT2sVmzG19CX4oDhs6oNdWS8R4djcZ7
API listening on /ip4/127.0.0.1/tcp/5001/http
Gateway (read only) listening on /ip4/127.0.0.1/tcp/8080/http
Web UI available at http://127.0.0.1:5001/webui
Daemon is ready
NodeError: Cannot call write after a stream was destroyed
    at doWrite (/Users/alan/.iim/dists/js-ipfs@0.36.4/node_modules/readable-stream/lib/_stream_writable.js:405:38)
    at writeOrBuffer (/Users/alan/.iim/dists/js-ipfs@0.36.4/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at ResponseStream.Writable.write (/Users/alan/.iim/dists/js-ipfs@0.36.4/node_modules/readable-stream/lib/_stream_writable.js:303:11)
    at BufferPeekStream.ondata (_stream_readable.js:696:22)
    at BufferPeekStream.emit (events.js:196:13)
    at BufferPeekStream.Readable.read (_stream_readable.js:491:10)
    at flow (_stream_readable.js:960:34)
    at emitReadable_ (_stream_readable.js:555:3)
    at onEofChunk (_stream_readable.js:519:5)
    at readableAddChunk (_stream_readable.js:239:5)
/Users/alan/.iim/dists/js-ipfs@0.36.4/node_modules/ipfs/src/cli/bin.js:9
  throw err
  ^

Error: Cannot call write after a stream was destroyed
    at doWrite (/Users/alan/.iim/dists/js-ipfs@0.36.4/node_modules/readable-stream/lib/_stream_writable.js:405:38)
    at writeOrBuffer (/Users/alan/.iim/dists/js-ipfs@0.36.4/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at ResponseStream.Writable.write (/Users/alan/.iim/dists/js-ipfs@0.36.4/node_modules/readable-stream/lib/_stream_writable.js:303:11)
    at BufferPeekStream.ondata (_stream_readable.js:696:22)
    at BufferPeekStream.emit (events.js:196:13)
    at BufferPeekStream.Readable.read (_stream_readable.js:491:10)
    at flow (_stream_readable.js:960:34)
    at emitReadable_ (_stream_readable.js:555:3)
    at onEofChunk (_stream_readable.js:519:5)
    at readableAddChunk (_stream_readable.js:239:5)
```

**Comment by jacobheun** [comment] 2019-07-02 10:40
Just adding some additional context before it leaves my brain:

This error was encountered heavily while there were numerous nodes spinning up and down on a local network (IPFS Camp). I'm assuming the thrashing of the network exposed a bug where we're not properly closing streams and bubbling that up when connections terminate, since the stack trace indicates we are writing to a dead connection/stream. A lot of nodes were leveraging MDNS while this was going on, but there were also plenty of browser and go-ipfs nodes running as well.

**Comment by lidel** [comment] 2019-07-05 11:56
I also got this error today while browsing websites via HTTP Gateway.

`BufferPeekStream` is present every time `Cannot call write after a stream was destroyed` occurs, and AFAIK gateway is the only place where we use `peek` from `buffer-peek-stream`: [js-ipfs:src/http/gateway/resources/gateway.js#L145-L162](https://github.com/ipfs/js-ipfs/blob/43ac3051a3066786d5ce0d6a305ddf46156d0c75/src/http/gateway/resources/gateway.js#L145-L162)

Which begs the question: is there a bug in `buffer-peek-stream`,  or is it just a canary in a coal mine and the bug is elsewhere?

ps. possible duplicate: https://github.com/libp2p/pull-mplex/issues/13

**Comment by jacobheun** [comment] 2019-07-05 12:16
It's possible the pipe call isn't properly forwarding errors. Using the streams `pipeline` method might help mitigate this. If Gateway is the only place we're using BufferPeekStream we should add a test for clients hanging up while we're streaming them a response and see if this causes the failure.

**Comment by lidel** [comment] 2019-07-05 15:00
I found a way to reproduce `Error: Cannot call write after a stream was destroyed`:

1. Open a single file, eg. http://127.0.0.1:9090/ipns/tr.wikipedia-on-ipfs.org/I/m/Mars_oppositions_2003-2018.png 
2. Open Console, go to Network tab, disable cache (with cache HTTP 304 makes it harder to reproduce)
3. Rapidly refresh page a few times to ensure one of requests is cancelled by the browser mid-fly
4. `jsipfs daemon` will die with `Error: Cannot call write after a stream was destroyed`

This happens even if I use `pipeline` [here](https://github.com/ipfs/js-ipfs/blob/43ac3051a3066786d5ce0d6a305ddf46156d0c75/src/http/gateway/resources/gateway.js#L160), it looks like it happens [here, inside of hapijs](https://github.com/ipfs/js-ipfs/blob/43ac3051a3066786d5ce0d6a305ddf46156d0c75/src/http/gateway/resources/gateway.js#L162), I will look into this, perhaps hapi is closing response stream while we are still piping to it.

**Closed** 2019-07-12 15:47 UTC
Labels: P1 - High, bug, difficulty:hard, ready
