### ISSUE TITLE
Overhaul libp2p-crypto

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#586] opened 2020-03-11 09:56 UTC
- **Version**: N/A
- **Platform**: N/A
- **Subsystem**: N/A

#### Description:

One of the pain points of development within a browser context is the **bundle size** of a web app, which easily gets quite big and makes web pages take longer times to run. In `js-libp2p` land, we have been working over the last months on reducing the bundle size of the library to the minimum possible, so that `js-libp2p` users in the browser don't need to have a large bundle size just for using this library.

One of the outstanding issues to have our bundle size in a considerably good shape is the crypto libraries that we need to carry. The JS ecosystem around cryptography is far from perfect, which has made us use several different libraries to achieve different cryptographic primitives.

Taking into account that `libp2p` is a composable and modular stack, most of the times `js-libp2p` bundle contains heavy crypto code that is not needed. In this context, `js-libp2p` crypto should be modular and pluggable, so that the users can bring just what they need instead of the all thing.

**Comment by maschad** [comment] 2023-09-28 18:35
Closing as duplicate of https://github.com/libp2p/js-libp2p/issues/2086

**Closed by maschad** 2023-09-28 18:35 UTC
Labels: kind/enhancement, exp/wizard, status/ready
